export { Navigation } from "./Navigation";
export { Hero } from "./Hero";
export { About } from "./About";
export { Experience } from "./Experience";
export { Skills } from "./Skills";
export { Projects } from "./Projects";
export { Testimonials } from "./Testimonials";
export { Contact } from "./Contact";
export { TerminalChatbot } from "./TerminalChatbot";
